name: Pull Request Checks

on:
  pull_request:

jobs:
  node-tests:
    name: Run Node Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 24.14.1
        uses: actions/setup-node@v4
        with:
          node-version: "24.14.1"

      - name: Make test script executable
        run: chmod +x ./scripts/test_all.sh

      - name: Run Node tests
        run: ./scripts/test_all.sh
